#!/usr/bin/env python3
"""
applepy-stubs — Generate .pyi type stubs from ApplePy macro metadata.

Usage:
    python3 applepy-stubs.py --module mylib --functions "greet:str->str,add:int,int->int" --classes "Counter:increment()->None,value()->int"
    
Or point it at a Swift source file to extract @PyFunction/@PyClass annotations:
    python3 applepy-stubs.py --swift Sources/mylib/mylib.swift --module mylib

Generates a .pyi file for IDE autocomplete (MyPy, Pyright).
"""

import argparse
import re
import sys
import os

# Swift → Python type mapping
TYPE_MAP = {
    "Int": "int",
    "Int32": "int",
    "Int64": "int",
    "UInt": "int",
    "Double": "float",
    "Float": "float",
    "Bool": "bool",
    "String": "str",
    "Void": "None",
}


def swift_type_to_python(swift_type: str) -> str:
    """Convert a Swift type annotation to Python type hint."""
    swift_type = swift_type.strip()

    # Optional<T> → Optional[T]
    if swift_type.endswith("?"):
        inner = swift_type[:-1]
        return f"Optional[{swift_type_to_python(inner)}]"

    # Array<T> → list[T]
    m = re.match(r"Array<(.+)>", swift_type)
    if m or swift_type.startswith("[") and swift_type.endswith("]"):
        if m:
            inner = m.group(1)
        else:
            inner = swift_type[1:-1]
        return f"list[{swift_type_to_python(inner)}]"

    # Dictionary<K,V> → dict[K, V]
    m = re.match(r"Dictionary<(.+),\s*(.+)>", swift_type)
    if m:
        return f"dict[{swift_type_to_python(m.group(1))}, {swift_type_to_python(m.group(2))}]"

    return TYPE_MAP.get(swift_type, swift_type)


def parse_swift_file(path: str):
    """Extract @PyFunction and @PyClass declarations from Swift source."""
    with open(path) as f:
        source = f.read()

    functions = []
    classes = []

    # Find @PyFunction func name(params) -> ReturnType
    for m in re.finditer(
        r"@PyFunction\s+func\s+(\w+)\s*\(([^)]*)\)\s*(?:->\s*(\w+[\w<>,?\s]*))?",
        source,
    ):
        name = m.group(1)
        params_str = m.group(2).strip()
        return_type = m.group(3) or "Void"

        params = []
        if params_str:
            for p in params_str.split(","):
                p = p.strip()
                parts = p.split(":")
                if len(parts) >= 2:
                    pname = parts[0].strip().split()[-1]  # handle "_ name" or "name"
                    ptype = parts[1].strip()
                    params.append((pname, ptype))

        functions.append((name, params, return_type))

    # Find @PyClass struct/class Name
    for m in re.finditer(r"@PyClass\s+(?:struct|class)\s+(\w+)", source):
        class_name = m.group(1)

        # Find methods within the class body (simplified)
        methods = []
        for mm in re.finditer(
            r"@PyMethod(?:\(\"([^\"]*)\"\))?\s+func\s+(\w+)\s*\(([^)]*)\)\s*(?:->\s*(\w+[\w<>,?\s]*))?",
            source,
        ):
            py_name = mm.group(1) or mm.group(2)
            swift_name = mm.group(2)
            params_str = mm.group(3).strip()
            return_type = mm.group(4) or "Void"

            params = []
            if params_str:
                for p in params_str.split(","):
                    p = p.strip()
                    parts = p.split(":")
                    if len(parts) >= 2:
                        pname = parts[0].strip().split()[-1]
                        ptype = parts[1].strip()
                        params.append((pname, ptype))

            methods.append((py_name, params, return_type))

        # Find init params
        init_params = []
        init_m = re.search(
            r"init\s*\(([^)]*)\)", source[m.start():]
        )
        if init_m:
            for p in init_m.group(1).split(","):
                p = p.strip()
                parts = p.split(":")
                if len(parts) >= 2:
                    pname = parts[0].strip().split()[-1]
                    ptype = parts[1].strip().split("=")[0].strip()
                    has_default = "=" in parts[1]
                    init_params.append((pname, ptype, has_default))

        classes.append((class_name, init_params, methods))

    return functions, classes


def generate_stub(module_name: str, functions, classes) -> str:
    """Generate .pyi stub content."""
    lines = [
        f'"""Type stubs for {module_name} (generated by applepy-stubs)."""',
        "",
        "from typing import Optional",
        "",
    ]

    for name, params, return_type in functions:
        py_params = ", ".join(
            f"{pname}: {swift_type_to_python(ptype)}" for pname, ptype in params
        )
        py_return = swift_type_to_python(return_type)
        lines.append(f"def {name}({py_params}) -> {py_return}: ...")
        lines.append("")

    for class_name, init_params, methods in classes:
        lines.append(f"class {class_name}:")

        # __init__
        if init_params:
            init_py_params = []
            for pname, ptype, has_default in init_params:
                py_type = swift_type_to_python(ptype)
                if has_default:
                    init_py_params.append(f"{pname}: {py_type} = ...")
                else:
                    init_py_params.append(f"{pname}: {py_type}")
            params_str = ", ".join(init_py_params)
            lines.append(f"    def __init__(self, {params_str}) -> None: ...")
        else:
            lines.append(f"    def __init__(self) -> None: ...")

        # Methods
        for py_name, params, return_type in methods:
            if py_name.startswith("__") and py_name.endswith("__"):
                # Dunder methods
                if py_name == "__repr__":
                    lines.append(f"    def __repr__(self) -> str: ...")
                elif py_name == "__str__":
                    lines.append(f"    def __str__(self) -> str: ...")
                else:
                    py_params = ", ".join(
                        f"{pname}: {swift_type_to_python(ptype)}"
                        for pname, ptype in params
                    )
                    py_return = swift_type_to_python(return_type)
                    if py_params:
                        lines.append(f"    def {py_name}(self, {py_params}) -> {py_return}: ...")
                    else:
                        lines.append(f"    def {py_name}(self) -> {py_return}: ...")
            else:
                py_params = ", ".join(
                    f"{pname}: {swift_type_to_python(ptype)}"
                    for pname, ptype in params
                )
                py_return = swift_type_to_python(return_type)
                if py_params:
                    lines.append(f"    def {py_name}(self, {py_params}) -> {py_return}: ...")
                else:
                    lines.append(f"    def {py_name}(self) -> {py_return}: ...")

        lines.append("")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate .pyi stubs from Swift source")
    parser.add_argument("--module", required=True, help="Module name")
    parser.add_argument("--swift", help="Path to Swift source file")
    parser.add_argument("--output", help="Output .pyi path (default: <module>.pyi)")
    args = parser.parse_args()

    if args.swift:
        if not os.path.exists(args.swift):
            print(f"Error: file not found: {args.swift}", file=sys.stderr)
            sys.exit(1)
        functions, classes = parse_swift_file(args.swift)
    else:
        print("Error: --swift is required", file=sys.stderr)
        sys.exit(1)

    stub = generate_stub(args.module, functions, classes)

    output_path = args.output or f"{args.module}.pyi"
    with open(output_path, "w") as f:
        f.write(stub)

    print(f"✅ Generated: {output_path}")
    print(f"   Functions: {len(functions)}")
    print(f"   Classes: {len(classes)}")


if __name__ == "__main__":
    main()
